DEBUG tests/libex29_tests.c:64: ---- RUNNING: ./tests/libex29_tests
DEBUG tests/libex29_tests.c:56: 
----- test_dlopen
DEBUG tests/libex29_tests.c:57: 
----- test_functions
DEBUG tests/libex29_tests.c:58: 
----- test_failures
[ERROR] (tests/libex29_tests.c:check_function:11: errno: None) Did not find fail on purpose function in the library build/libex29.so: build/libex29.so: undefined symbol: fail on purpose
[ERROR] (tests/libex29_tests.c:test_failures:40: errno: None) fail_on_purpose should fail.
DEBUG tests/libex29_tests.c:64: ---- RUNNING: ./tests/libex29_tests
DEBUG tests/libex29_tests.c:56: 
----- test_dlopen
DEBUG tests/libex29_tests.c:57: 
----- test_functions
DEBUG tests/libex29_tests.c:58: 
----- test_failures
DEBUG tests/libex29_tests.c:59: 
----- test_dlclose
DEBUG tests/libex29_tests.c:64: ---- RUNNING: ./tests/libex29_tests
DEBUG tests/libex29_tests.c:56: 
----- test_dlopen
DEBUG tests/libex29_tests.c:57: 
----- test_functions
DEBUG tests/libex29_tests.c:58: 
----- test_failures
DEBUG tests/libex29_tests.c:59: 
----- test_dlclose
